---
- name: Clone Odoo repository
  ansible.builtin.git:
    repo: 'https://github.com/odoo/odoo.git'
    dest: '{{ odoo_install_dir }}'
    version: '{{ odoo_version }}'
    depth: 1
    single_branch: true
    update: false
  become: true

- name: Run Odoo setup script
  ansible.builtin.command:
    cmd: ./setup/debinstall.sh
    chdir: '{{ odoo_install_dir }}'
  become: true
  args:
    creates: '/home/.odoo_setup_done'

- name: Create a marker file to indicate Odoo setup is done
  ansible.builtin.file:
    path: '/home/.odoo_setup_done'
    state: touch
    mode: '0644'
  become: true

- name: Copy the odoorc config file
  ansible.builtin.template:
    src: "odoorc.j2"
    dest: "{{ odoo_install_dir }}/.odoorc"
    mode: '0644'

- name: Create a systemd service for Odoo
  ansible.builtin.template:
    src: "odoo.service.j2"
    dest: "/etc/systemd/system/odoo.service"
    mode: '0644'
  notify:
    - Reload systemd
    - Restart odoo
