---

- name: Ensure directory for SSL certificates exists
  ansible.builtin.file:
    path: /etc/ssl/nginx
    state: directory
    mode: '0755'
    owner: root
    group: root

- name: Generate a private key
  community.crypto.openssl_privatekey:
    path: /etc/ssl/nginx/server.key
    size: 2048
    type: RSA
  register: privatekey

- name: Set strict permissions for private key
  ansible.builtin.file:
    path: /etc/ssl/nginx/server.key
    mode: '0600'
    owner: root
    group: root

- name: Generate a self-signed certificate
  community.crypto.x509_certificate:
    path: /etc/ssl/nginx/server.crt
    privatekey_path: /etc/ssl/nginx/server.key
    provider: selfsigned
    selfsigned_notAfter: "+365d"
    selfsigned_digest: "sha256"
    selfsigned_create_subject_key_identifier: "create_if_not_provided"
    selfsigned_version: 3
